### ISSUE TITLE
Sort scoreboard according to gold count

### ISSUE THREAD

**Issue by Steanky** [zapzombies/zap-community#10]
**Is your feature request related to a problem? Please describe.**
its confusing when i instinctively look at the top of the list in the middle of a round and think i have more gold then i do, or vice versa

**Describe the solution you'd like**
The amount of money you have should be at the top of the list of people in the game

**Describe alternatives you've considered**

**Additional context**

**Comment by thamid-gamer** [comment]
didn't I do this a while ago? did it break lol

**Comment by Steanky** [comment]
i never bothered to test if it was implemented because i literally don't notice or care about the scoreboard order
if it's implemented, this should be closed

**Comment by thamid-gamer** [comment]
(unless someone shows that it broke then closed)
