### ISSUE TITLE
Bosses should have health bars

### ISSUE THREAD

**Issue by Steanky** [zapzombies/zap-community#12]
**Is your feature request related to a problem? Please describe.**
It's hard to tell how much HP a boss has remaining.

**Describe the solution you'd like**
Bosses should have a healthbar above their head.

**Describe alternatives you've considered**

**Additional context**

**Comment by JolindaThique** [comment]
There needs to be a non-MythicMobs alternative to this or another hack to it. Anything dependent on damage received in MM is broken, because someone thought it'd be a good idea to not take all sources of damage into consideration.

**Comment by Steanky** [comment]
This mechanic? 
https://mythicmobs.net/manual/doku.php/skills/mechanics/barcreate

**Comment by JolindaThique** [comment]
That's the wither boss bar. I assume you all want the Hypixel-esque one.

**Comment by Steanky** [comment]
Are you sure this is the wither boss bar? I only ask because the page says it allows multiple "styles" including various "segmented" options, which makes it seem like they're talking about something more like what Hypixel does.

**Comment by tachibanayui** [comment]
![image](https://user-images.githubusercontent.com/33594017/133886718-912e8fab-2959-4e44-b95a-e7cbbbd5aaef.png)
This is the bossbar, the style field meant different kinds of it. Segment_6 meant there are 6 small bars in a bossbar, Segment_10 is 10 small bars and so on

This is an example of different styles of bossbar
![image](https://user-images.githubusercontent.com/33594017/133886745-8beb30cf-4307-4bfe-b5e7-d367111b3db1.png)

**Comment by Steanky** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/33594017/133886718-912e8fab-2959-4e44-b95a-e7cbbbd5aaef.png)
> This is the bossbar, the style field meant different kinds of it. Segment_6 meant there are 6 small bars in a bossbar, Segment_10 is 10 small bars and so on
> 
> This is an example of different styles of bossbar
> ![image](https://user-images.githubusercontent.com/33594017/133886745-8beb30cf-4307-4bfe-b5e7-d367111b3db1.png)

Oh that's pretty cool you can do that with vanilla

**Comment by tachibanayui** [comment]
Yeah, they added it in 1.13. You can even spawn one using command

**Comment by Steanky** [comment]
Health bars got added.
