### ISSUE TITLE
Increase the revive hitbox

### ISSUE THREAD

**Issue by nekorii04** [zapzombies/zap-community#19]
**Is your feature request related to a problem? Please describe.**
Hello. Yes. Please increase revive hitboxes. They're so small. 

**Describe the solution you'd like**
Increase Revive hitboxes

**Describe alternatives you've considered**
Increase Revive hitboxes

**Additional context**
Increase Revive hitboxes

**Comment by Ducks9920** [comment]
do it bro

**Comment by nekorii04** [comment]
I agree

**Comment by nekorii04** [comment]
@Eyeball#3284

**Comment by nekorii04** [comment]
<@395764893430841363>

**Comment by thamid-gamer** [comment]
increase it how much

**Comment by Steanky** [comment]
> 
> 
> increase it how much

like one block would be enough
don't remember if we hardcoded it or if it's configurable

**Comment by Ducks9920** [comment]
make it the same hitbox as the body

**Comment by nekorii04** [comment]
I remember seeing something about it in the configs, I will look into it later

**Comment by nekorii04** [comment]
> > increase it how much
> 
> like one block would be enough
> don't remember if we hardcoded it or if it's configurable

theres a  "reviveRadius" option in the map config
