### ISSUE TITLE
Remove Combat Knife

### ISSUE THREAD

**Issue by Ducks9920** [zapzombies/zap-community#20]
**Is your feature request related to a problem? Please describe.**
Combat knife is useless because it only increase your DPS while reloading which would only be needed early game and by not that much. Late game you'll want to use Steanker 100% of the time. There's no need have a lucky chest weapon that's only there to waste 1k gold.

**Describe the solution you'd like**
remove it

**Describe alternatives you've considered**
remove

**Additional context**
remov

**Comment by nekorii04** [comment]
hes telling the truth

**Comment by JolindaThique** [comment]
No. This is the flamethrower of Hades' Dominion.

**Comment by Ducks9920** [comment]
even flamethrower is useful in bb sr

**Comment by WikidClix** [comment]
remove it
