### ISSUE TITLE
Bugged Egotist in Round 39

### ISSUE THREAD

**Issue by nekorii04** [zapzombies/zap-community#23]
**Describe the bug**
In Round 39, atleast one Egotist always ends up being bugged and invincible

**Where did the bug occur**
map_nt

**To Reproduce**
1. go map_nt
2. reach round 39
3. kill everything
4. bugged mob

**Expected behavior**
its supposed to die after you kill it

**Screenshots**

https://user-images.githubusercontent.com/90960152/134145244-47c52ced-e2cf-4280-b9a8-604746e9497e.mp4

**Comment by nekorii04** [comment]
I agree

**Comment by Steanky** [comment]
Going to high-priority this. Also, it may not be a config issue (but I will look into it)

**Comment by JolindaThique** [comment]
Not a config issue (unless Consume is making them invincible (it SHOULDN'T), which I can remove.) If this isn't the issue, there could be a bug with Steank's slowFireRate mechanic used for the boss itself.

**Comment by JolindaThique** [comment]
Consume was commented out yesterday.

**Comment by Steanky** [comment]
Has this happened again recently (within the past 3 days or so)

**Comment by nekorii04** [comment]
the last time i've done a cheated r40 run with tachi i haven't noticed anything, but i wil ltest again once i have time for it

**Comment by Steanky** [comment]
@nekorii04 any update on this?

**Comment by nekorii04** [comment]
playtesting rn, will go godmode if we fail :kindacringeiflikousesit:

**Comment by nekorii04** [comment]
doesnt appear to happen anymore
