### ISSUE TITLE
KnockbackFactor should work on melee attacks.

### ISSUE THREAD

**Issue by JolindaThique** [zapzombies/zap-community#24]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when people are hitting MY golems and dogs to cheese them. 😤

**Describe the solution you'd like**
KnockbackFactor parameter should work on melee from any source too. Knives, hoes, pickaxes, fists, etc.

**Describe alternatives you've considered**
None. Frick you.

**Additional context**
Context: frick you.

**Comment by Ducks9920** [comment]
I disagree, it's extremely useful while having to MUI

**Comment by JolindaThique** [comment]
If a mob is meant to take 0% knockback, then it's meant to take 0% knockback from ALL sources. I shouldn't have put this as a feature request but as a bug.

**Comment by Steanky** [comment]
Fixed in latest patch
