### ISSUE TITLE
Extra weapon puts weapon in wrong slot

### ISSUE THREAD

**Issue by WikidClix** [zapzombies/zap-community#28]
**Describe the bug**
Extra Weapon is broken help help help the slot for 3rd weapon is in the slot next to perks 

**Where did the bug occur**
map_NT

**To Reproduce**
get Extra Weapon

**Expected behavior**
the slot to be in the 4TH hotbar space instead of the 6th or soemthing

**Screenshots**
<img width="1440" alt="Screen Shot 2021-09-23 at 5 44 54 PM" src="https://user-images.githubusercontent.com/91292448/134590493-f2b1b05d-499f-477e-9297-d8ebab291c9b.png">

**Comment by Steanky** [comment]
actually i reflex assigned thamid but this may be a config issue, let me check

**Comment by Steanky** [comment]
yeah idk why it's doing this

**Comment by Steanky** [comment]
This should be fixed now
