### ISSUE TITLE
Perk Vending Machine for Test Map 2

### ISSUE THREAD

**Issue by nekorii04** [zapzombies/zap-community#30]
**Is your feature request related to a problem? Please describe.**
Add a perk vending machine so I can use it in test map 2

**Describe the solution you'd like**
Vending Machine with üerls

**Describe alternatives you've considered**
Vending machine wIth pErks

**Additional context**
perks

**Comment by tachibanayui** [comment]
Probably set this to low priority because we are still trying to fix our code

**Comment by JolindaThique** [comment]
This should be closed because iirc we are going to include perks in the Lucky Chest itself.
