### ISSUE TITLE
Nerf Pig dmg r2-4

### ISSUE THREAD

**Issue by Ducks9920** [zapzombies/zap-community#32]
**Is your feature request related to a problem? Please describe.**
Pigs can kill you way too easily when you have no way to defend yourself r2-4.

**Describe the solution you'd like**
Nerf their dmg r2-4 by 33%

**Describe alternatives you've considered**
Sending them directly to the depths of the abyss so that they may never return.

**Additional context**
look at these
it's subnormal

https://user-images.githubusercontent.com/91029590/134794084-0546de8b-2510-4ed5-be8e-33ee01e28e24.mp4

https://user-images.githubusercontent.com/91029590/134794171-de781115-1cc5-4e92-86e2-f7706941d870.mp4

https://user-images.githubusercontent.com/91029590/134794172-1fbe5ddb-59c8-4851-ae7b-36ded7a8719a.mp4

https://user-images.githubusercontent.com/91029590/134794105-34a3af6a-5554-4676-8ca4-9a4ad741bdc6.mp4

**Comment by tachibanayui** [comment]
I think they are fine for 4 players because the number of them

**Comment by tachibanayui** [comment]
I play a lot of trio/quad game and it seem perfectly fine

**Comment by Ducks9920** [comment]
it's JUST r2-4
no one will care that r2-4 are too easy in trio/quad, but there are people complaining that it's too annoying in solo

**Comment by tachibanayui** [comment]
This map is designed for 4 players, not solo

**Comment by tachibanayui** [comment]
If we nerf the pig in r2-4, people playing quad will complain it is too easy

**Comment by Steanky** [comment]
Labelling as "wontfix" for several reasons
a) the game is balanced for 4 players, not 1. we can't start making balancing changes just for soloing. soloing is not supposed to be easy and you should expect to die a lot
b) all of these videos are examples of human error, not the game being imbalanced. you can't just let yourself get hit by the pigs; this isn't hypixel normal difficulty
c) i have tested solo through r1-5 myself and had absolutely no problems with the pigs
d) other players do not have problems with the pigs

if enough people come out and say they have an issue with them, i will reconsider, but for now there won't be any changes

**Comment by Steanky** [comment]
Poll results are in favor of no nerf so closing this
