### ISSUE TITLE
Power-up configs shouldn't use the 0-based index for rounds

### ISSUE THREAD

**Issue by JolindaThique** [zapzombies/zap-community#34]
**Is your feature request related to a problem? Please describe.**
It's confusing. That's it.

**Describe the solution you'd like**
Title. Start with 1 for round 1, etc. instead of 0.

**Describe alternatives you've considered**
Make it a -1-based index so there's even more confusion between both coders and those doing the configuring. But seriously, there is no alternative.

**Additional context**
None.

**Comment by Steanky** [comment]
if it's a 1-based index, we then need to subtract 1 from every round, since we use a 0-based index internally (otherwise we just wouldn't use the first element of the round list)

**Comment by JolindaThique** [comment]
How much overhead does that really add, though?

**Comment by Steanky** [comment]
Not talking about overhead - it's confusing for us to have to translate between 0-based and non-zero based. we're already doing it once (to display rounds)

**Comment by JolindaThique** [comment]
Seems like a lose-lose situation then.

**Comment by tachibanayui** [comment]
@Steanky we should take this into consideration when we remake arenaapi

**Comment by Steanky** [comment]
we should either use zero-based for everything or 1-based for everything, translating between the two constantly is asking for bugs

**Comment by thamid-gamer** [comment]
closing because we reached consensus and matlab is terrible
