### ISSUE TITLE
 Mobs getting stuck in a pair of stairs

### ISSUE THREAD

**Issue by JolindaThique** [zapzombies/zap-community#35]
**Describe the bug**
Mobs get stuck in stair-pairs and can't move out.

**Where did the bug occur**
Hades' Dominion.

**To Reproduce**
1. Join Hades' Dominion.
2. Camp somewhere where there are stairs + upside-down stairs on top.
3. Observe it happening somehow (whether by shooting or them jumping into it).

**Expected behavior**
They move out of there.

**Screenshots**

![2021-09-26_17 09 03](https://user-images.githubusercontent.com/66624445/134818478-aa993a88-914d-4599-82ae-758082558d96.png)
**Additional context**
None.

**Comment by Steanky** [comment]
Closed for duplicate (I already opened an issue for this, see #25)
