### ISSUE TITLE
Mob spawn in unopened room 

### ISSUE THREAD

**Issue by tachibanayui** [zapzombies/zap-community#37]
**Describe the bug**
Pigs spawn in r7 right after we open Warped

**Where did the bug occur**
Hades' Dominion

**To Reproduce**
1. Play until r7
2. Open Warped Forest

**Expected behavior**
Pigs should not be spawned in closed rooms

**Screenshots**
![image](https://user-images.githubusercontent.com/33594017/135315408-7fc4fa4c-1784-4631-bf61-523401011f73.png)

**Comment by nekorii04** [comment]
those are deco pigs, ignore them

**Comment by tachibanayui** [comment]
lmao

**Comment by nekorii04** [comment]
+ there are no windows there + that is crimson township

close this

**Comment by Steanky** [comment]
Can confirm, the pigs are for decoration and don't count towards the # of active mobs
