### ISSUE TITLE
Make the colors in those boss spawn titles work

### ISSUE THREAD

**Issue by nekorii04** [zapzombies/zap-community#39]
**Is your feature request related to a problem? Please describe.**
t for title

**Describe the solution you'd like**
make it look like this
![2021-09-30_17 32 40](https://user-images.githubusercontent.com/90960152/135485958-53fba732-9574-46a8-93ea-c6e095ccd34e.png)
and not this
![2021-09-30_16 34 09](https://user-images.githubusercontent.com/90960152/135486011-80af1f60-153d-4302-a2df-0f6bc3829e91.png)

**Comment by thamid-gamer** [comment]
if anyone wants to fix this, use the legacycomponentserializer where the title is sent OR use minimessage and change the config

**Comment by JolindaThique** [comment]
Also either
a) add a placeholder for ' or
b) support the MM placeholder, which is <&sq>

**Comment by thamid-gamer** [comment]
using minimessage, adjust the configs as you want as IDK how
