### ISSUE TITLE
Invincibility

### ISSUE THREAD

**Issue by Steanky** [zapzombies/zap-community#4]
**Describe the bug**
You can obtain invincibility to all damage.

**Where did the bug occur**
Hades' Dominion

**To Reproduce**
This is the hard part. I believe it had to do with my shitty hotspot WiFi. Basically, my theory is that because I had such bad inconsistent WiFi, when I joined wikids party and he warped me into map_nt, I retained the invincibility I had from the lobby. I believe this due to the fact I couldn’t take any damage at all; not from zombies, not from fall damage, not from anything. Also, it was a very laggy process joining the game, who knows what happened. I will try my absolute hardest to replicate this tomorrow, but a teammate is NECESARRY in order for this to work. If you don’t have any teammates, the mobs won’t agro you or you won’t even get it to work.

**Expected behavior**
I should not have invincibility

**Screenshots**

**Additional context**

**Comment by Steanky** [comment]
Assigning everyone to this because I have absolutely no idea what caused this, or if it's still a thing. More information is needed, so I'll keep the report open.

**Comment by tachibanayui** [comment]
oh btw `#1` mean you want to reference another issue
![image](https://user-images.githubusercontent.com/33594017/133878791-e9855787-05dc-4a05-a0b0-412a60131565.png)

**Comment by Steanky** [comment]
Lol I just copied Kai's message and didn't notice it had `#1` in it

**Comment by tachibanayui** [comment]
> Assigning everyone to this because I have absolutely no idea what caused this, or if it's still a thing. More information is needed, so I'll keep the report open.

Same we need more info

**Comment by Steanky** [comment]
I am going to close this for now, because aside from forgetting to disable godmode this has not happened to anybody
