### ISSUE TITLE
Add /zap giveGold function for godmode games

### ISSUE THREAD

**Issue by nekorii04** [zapzombies/zap-community#40]
**Is your feature request related to a problem? Please describe.**
t for title

**Describe the solution you'd like**
t for title

**Comment by thamid-gamer** [comment]
is godmode just creative or?

**Comment by JolindaThique** [comment]
godmode is an Essentials command for invincibility

**Comment by JolindaThique** [comment]
(I highly advise against making anything Essentials-related as a dependency of anything ZAP. Screw that plugin and everything it stands for. Make it available to developers.)

**Comment by JolindaThique** [comment]
someone close this because Steank just implemented it today
