### ISSUE TITLE
Mobs still get stuck on stairs and slabs (and other places)

### ISSUE THREAD

**Issue by nekorii04** [zapzombies/zap-community#41]
**Describe the bug**
mobs get stuck on stairs and slabs

**Where did the bug occur**
ma pnt

**To Reproduce**
1. play
2. go to later rounds
3. stuck mobs NO WAY NO WAY

**Expected behavior**
they're not supposed to be stuck

**Screenshots*
![2021-09-30_16 57 30](https://user-images.githubusercontent.com/90960152/135486307-e649cf44-1fd1-42d6-a472-cee2fa1e9a92.png)
*
![2021-09-30_16 58 08](https://user-images.githubusercontent.com/90960152/135486318-f56e1edd-6c37-4d9e-9147-01071d504681.png)
![2021-09-30_16 59 09](https://user-images.githubusercontent.com/90960152/135486325-2a3ff4ef-38d3-443e-ade6-2ff4828634ba.png)
![2021-09-30_16 59 39](https://user-images.githubusercontent.com/90960152/135486333-d1b1e2c9-5d2c-4a0e-bab3-00b0eac7720b.png)

![2021-09-30_17 02 45](https://user-images.githubusercontent.com/90960152/135486342-de686fc9-b141-46f8-a78f-59437d43974e.png)

**Comment by nekorii04** [comment]
steank be like
![im_in_unbearable_pain](https://user-images.githubusercontent.com/90960152/135488003-bbfabd68-0b5b-42b6-8d84-81f8b65c1237.gif)

**Comment by Steanky** [comment]
Tested latest cleanup, went to 2nd and 3rd screenshot locations with like 69 witches, could not get them to be stuck
