### ISSUE TITLE
Unnecessary spacing on knockdown message

### ISSUE THREAD

**Issue by nekorii04** [zapzombies/zap-community#44]
**Is your feature request related to a problem? Please describe.**
there's one space in the knockdown message that triggers my ocd

**Describe the solution you'd like**
remove that one space

**Describe alternatives you've considered**
![image](https://user-images.githubusercontent.com/90960152/135488571-f7d42f6b-2432-47f6-8b5f-ea68237d9401.png)
![image](https://user-images.githubusercontent.com/90960152/135488579-369d68d9-be36-4fbe-9c2f-131d933359aa.png)
make it look liokoe this
![image](https://user-images.githubusercontent.com/90960152/135488726-54f5dcc1-8094-4fc5-9e10-4c2a2e9a9460.png)

**Comment by Steanky** [comment]
Should be fixed on latest cleanup

**Comment by Steanky** [comment]
Not closing until patch though
