### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by EmperorKai2** [zapzombies/zap-community#45]
Suggestion add virtual fisher bot, make it a channel, then mute the channel pls it's a super fun and popular bot made by a zombies player who's nice names saltspreader

**Comment by nekorii04** [comment]
no

**Comment by nekorii04** [comment]
use tachis zombies bot instead

**Comment by EmperorKai2** [comment]
Shat up vf is good

**Comment by JolindaThique** [comment]
Please don't make joke suggestions.

I wish I was able to close issues.

**Comment by Steanky** [comment]
If you want discord bots, just ask me for them in Discord, this is unnecessary
