### ISSUE TITLE
ZombiesNPC improvements because tahmid will never do it (#blameTahmid)

### ISSUE THREAD

**Issue by nekorii04** [zapzombies/zap-community#46]
**Is your feature request related to a problem? Please describe.**
the zombiesnpc system SUCKS

**Describe the solution you'd like**
- add a toggle for the Play Zombies hologram
- an option to change the hologram
- and change the maps zombiesnpc has
- equipment for the NPC
**Additional context**
thx

#blame tahmid

**Comment by thamid-gamer** [comment]
Good luck getting someone to do it because there are more pressing issues
hahahhahhahahhahahhahahahahahahhahahahahahahhahahahhahahahahaahahhahaha

**Comment by nekorii04** [comment]
fku

**Comment by Liko42069** [comment]
cancel tamid

**Comment by thamid-gamer** [comment]
is everything you want from the npcs listed?
if you want super complicated stuff then I would need to use citizens API, but I'm not familiar with it at all and it might be difficult to work with

**Comment by nekorii04** [comment]
That's all i need rn
