### ISSUE TITLE
When you die, you too should get the death sound + message in chat.

### ISSUE THREAD

**Issue by JolindaThique** [zapzombies/zap-community#50]
**Is your feature request related to a problem? Please describe.**
It prevents some confusion. Very useful if you play while being tired as fuck and you don't register you died at first because there's 0 actual sign you did (other than the countdown.)

**Describe the solution you'd like**
The dead person also has the death sound play to them and they get the message about their own death in chat.

**Comment by nekorii04** [comment]
yes
