### ISSUE TITLE
Falling through blocks when dying

### ISSUE THREAD

**Issue by Steanky** [zapzombies/zap-community#6]
**Describe the bug**
Dying (?) or getting knocked down sometimes results in your spectator falling through the floor

**Where did the bug occur**
Hades' Dominion, in the staircase leading from Warped Settlement to Shattered Canyon

**To Reproduce**
Die in a specific place. Unsure of what that place is. More information needed.

**Expected behavior**
My spectator should have been free to fly around the map

**Screenshots**
![image](https://cdn.discordapp.com/attachments/870024141913354280/879486211406856242/2021-08-23_13.47.46.png)

**Additional context**

**Comment by Steanky** [comment]
Not sure if this is still a problem? I suspect it is.

**Comment by tachibanayui** [comment]
Should we use proper spectator mode instead of flying adventure mode?

**Comment by Steanky** [comment]
> 
> 
> Should we use proper spectator mode instead of flying adventure mode?

That would work, We could also maybe give the player a teleport compass like in hypixel, but that's a lot of effort for the time being

**Comment by thamid-gamer** [comment]
> Should we use proper spectator mode instead of flying adventure mode?

doesn't spectator mode hide the gui

**Comment by nekorii04** [comment]
i filled some holes where you can glitch in when you get knocked, @Steanky you can close this
