### ISSUE TITLE
Private Space

### ISSUE THREAD

**Issue by tigerboy06** [zapzombies/zap-community#60]
Ok so, we all know we sometimes get items from nice builders (like EmperorKai) or other people... but we lose them as soon as we join a game.. so there are two solutions rn:

- accept the loss
- never play again

So the only rational thing to do is never play again, but in our hearts we dont want that.
To solve this problem I came up with this solution:

- Place an enderchest at spawn and add the permission to open and use enderchest to all roles (player, patreon etc)

For all who only speak LOLCat heres the Text in Lolcat: 
(4 ALL HOO ONLY SPEEK ENGLIZ HEREZ TEH TEXT IN LOLCAT:)

K SO, WE ALL KNOE WE SOMETIMEZ GIT ITEMS FRUM NICE BUILDERS (LIEK EMPERORKAI) OR OTHR PEEPS... BUT WE LOSE THEM AS SOON AS WE JOIN GAME.. SO THAR R 2 SOLUSHUNS RN:

- ACCEPT TEH LOS
- NEVR PULAY AGAIN

SO TEH ONLY RASHUNAL TING 2 DO IZ NEVR PULAY AGAIN, BUT IN R HEARTS WE DOAN WANTS DAT.
2 SOLVE DIS PROBLEM I CAME UP WIF DIS SOLUSHUN:

- PLACE AN ENDERCHEST AT SPAWN AN ADD TEH PERMISHUN 2 OPEN AN USE ENDERCHEST 2 ALL ROLEZ (PLAYR, PATREON ETC)

**Comment by JolindaThique** [comment]
You were _not_ supposed to receive any cosmetics whatsoever. Kai went against the rules and maladvertised a feature that isn't going to be implemented for something as silly as panda killing and tryhard parkour (that only lasts for a single server session.) Yes, I do realize this sets a very bad precedent for us and thus there will be sanctions among the staff.

I'd close this but Steank didn't give me permission to do so.
