### ISSUE TITLE
Overall changes

### ISSUE THREAD

**Issue by CLUBMASTER28** [zapzombies/zap-community#65]
One problem is the fact that the aiming is weird. It seems like the hitbox of ennemies is really low , but it could also be the hitbox of the shot. It's really hard to aim at people not moving towards you. Alternative: make hitbox bigger

I know most players are really good ones , but some aren't as experienced and i feel like the difficulty is really high , some mobs early on should be nerfed like the pig, reduce his hp perhaps , reduce archer damage and black dude hp . Another solution would be to give money at the end of each round. (speed increase too but that has been said already in another report)

Might not be related to the server but me and friends had freeze issues frequently so idk.

**Comment by thamid-gamer** [comment]
Please post separate suggestions in different issue reports

1. mojang decides hitboxes and we follow them, we might consider changing making Zombie hitboxes as tall as they would be with player heads but pig hitboxes will always be kind of strange

2. this has been a point of contention for a while, but the current belief is that pigs shall not be nerfed. archers and smoldering golems are generally considered to be balanced, you will get used to them.

3. mojang bug, fix is to fabric + sodium/lithium/phosphor

**Comment by JolindaThique** [comment]
The map is meant to be for veterans. There is an easier map coming up for those new. + everything Tahmid already said

Closing.
