### ISSUE TITLE
/zap zombies gamereport

### ISSUE THREAD

**Issue by Sternig** [zapzombies/zap-community#69]
**Is your feature request related to a problem? Please describe.**
/zap zombies gamereport

something like this maybe
![Screenshot_1653](https://user-images.githubusercontent.com/90960152/136787803-7a5d64a0-1ad8-455c-8ac2-f4492e9b8977.png)
![image](https://user-images.githubusercontent.com/90960152/136788731-5d7f1f5c-982f-46e5-83fb-d8cd5820d2a5.png)

/tellraw @a ["",{"text":"-                                                    -","strikethrough":true,"color":"white"},{"text":"\n"},{"text":"\u22d9 1/3","color":"gray"},{"text":" ZAP","bold":true,"color":"aqua"},{"text":" Gamereport at ","color":"dark_aqua"},{"text":"06:09:42 UTC; 06/09/2069","bold":true,"color":"aqua"},{"text":"\n\n   "},{"text":"9/15 Active Games","bold":true,"color":"dark_aqua"},{"text":"\n   1/9"},{"text":" ec70bcaf-702f-4bb8-b48d-276fa52a780c","bold":true,"color":"aqua"},{"text":"\n         "},{"text":"EmperorKai, VeryAverage, edcr, creepir","color":"dark_aqua"},{"text":"\n        "},{"text":"Hades' Dominion:","bold":true,"color":"red"},{"text":" Round 6 - 6:09 ","color":"red"},{"text":"[WARP]","bold":true,"underlined":true,"color":"dark_aqua"},{"text":"\n\n   2/9 "},{"text":"31ee3877-dbd8-423a-95e4-9181b8acfe74","bold":true,"color":"aqua"},{"text":"\n         "},{"text":"thamid, Steank, TachibanaYui, YourMom","color":"dark_aqua"},{"text":"\n       "},{"text":"Hades' Dominion:","bold":true,"color":"red"},{"text":" Round 9 - 16:09 ","color":"red"},{"text":"[WARP]","bold":true,"underlined":true,"color":"dark_aqua"},{"text":"\n\n   3/9 "},{"text":"6458e77a-f565-4374-9de7-c2a20be572f3","bold":true,"color":"aqua"},{"text":"\n         "},{"text":"FuckYou, NeverGonna, Give, YouUp","color":"dark_aqua"},{"text":"\n       "},{"text":"Hades' Dominion:","bold":true,"color":"red"},{"text":" Round 35 - 2:03:12 ","color":"red"},{"text":"[WARP]","bold":true,"underlined":true,"color":"dark_aqua"},{"text":"\n"},{"text":"      ...","bold":true,"color":"dark_aqua"},{"text":"\n\n"},{"text":"Click ","color":"aqua"},{"text":"here","bold":true,"underlined":true,"color":"dark_aqua"},{"text":" for the next page","color":"aqua"},{"text":"\n"},{"text":"-                                                    -","strikethrough":true}]

**Comment by tahmid-23** [comment]
done

**Comment by Sternig** [comment]
> done

lets fucking go
