### ISSUE TITLE
 the *NEW PB* thing

### ISSUE THREAD

**Issue by WikidClix** [zapzombies/zap-community#71]
**Describe the bug**
the "you beat round 10 with xx:xx time" is 1. only in seconds, and 2. appears when you REACH r10 not when you beat it. same for r20 30 40 ofc

**Where did the bug occur**
map underscore NT

**To Reproduce**
play solo 
die early round
rage
punch wall and make a hole
realize you made a hole
play solo
get to round 10

**Expected behavior**
when you beat round 10 the thing shows up in xx:xx.xx format (with or without decimals)

**Screenshots**

![Photo on 10-11-21 at 11 14 PM](https://user-images.githubusercontent.com/91292448/136885300-788f0261-6532-406e-b140-f42d692a77f3.jpg)

these is a problem

**Comment by WikidClix** [comment]
> I don't understand part 1

it shows up as "629.3s" instead of "10:48.34" or whatever

**Comment by Ducks9920** [comment]
![Screenshot (333)](https://user-images.githubusercontent.com/91029590/137649603-cf5a2fb3-bc6f-422e-9c6b-33c1cc88a5eb.png)

It should instead say: "You beat round 10 in xx:xx.xx!"

**Comment by thamid-gamer** [comment]
I agree but I'm lazy and also I have to format timestamps with components which is a bit annoying

**Comment by nekorii04** [comment]
show me how to do it i will do it for you

**Comment by tahmid-23** [comment]
soon to be fixed
