### ISSUE TITLE
[Typo]  inviting players w/o permission has double punctuation

### ISSUE THREAD

**Issue by ShinyTillDawn** [zapzombies/zap-community#75]
**Describe the bug**
When partying a person w/o being the leader, there is an extra period after the exclamation point after being told you are not allowed to invite players.

**Where did the bug occur**
Happens anywhere

**To Reproduce**
1. Join a party
2. Type "/p invite [someone's IGN who is online]
3. See error

**Expected behavior**
The error either ending in a period or an exclamation mark.

**Screenshots**
[https://prnt.sc/1wfrcwz](https://prnt.sc/1wfrcwz)

**Additional context**
If I should submit typos somewhere else, let me know.

**Comment by tahmid-23** [comment]
soon to be fixed
