### ISSUE TITLE
[BALANCING] Make r39 harder

### ISSUE THREAD

**Issue by Ducks9920** [zapzombies/zap-community#77]
**Is your feature request related to a problem? Please describe.**
Round 39 is way too easy compared to other rounds from r33-39 since it doesn't have a mini-boss.

**Describe the solution you'd like**
Add a mini-boss to r39.

**Describe alternatives you've considered**
Simply buffing the pre-existing regular mobs, but that would be boring.

**Additional context**
N/A

**Comment by nekorii04** [comment]
also they were supposed to shoot you 20 times a second but it doesnt work so blame bukkitnmojang tahmid whoever

**Comment by Ducks9920** [comment]
> but.. there is a mini boss called pride

If there is it didn't spawn at all

**Comment by Ducks9920** [comment]
should i delete this and make a separate issue for r39 boss not spawning then?
