### ISSUE TITLE
[BUG] "No permission" messages incorrectly showing up

### ISSUE THREAD

**Issue by Ducks9920** [zapzombies/zap-community#81]
**Describe the bug**
Despite being able to properly execute /zap quit, you will still receive multiple error messages claiming that you do not have permission to use the command.

**Where did the bug occur**
Main lobby

**To Reproduce**
1. Join a game
2. Execute /zap quit
3. Observe the error messages

**Expected behavior**
There should not be an error message.

**Screenshots**
![2021-10-21_18 12 49](https://user-images.githubusercontent.com/91029590/138377898-4dd87c0d-115b-4f1e-8c6a-1343226ddc54.png)

**Comment by tahmid-23** [comment]
Is this still happening to anyone

**Comment by Sternig** [comment]
no

**Comment by tahmid-23** [comment]
Comment or open a new issue if this still happens
