### ISSUE TITLE
Ingame timer adds +1 second 

### ISSUE THREAD

**Issue by Sternig** [zapzombies/zap-community#91]
**Describe the bug**
at the end of the game when you win or lose idk it adds a second to the timer
this is visible on the lb, it shows 27:57 as wr while ingame it showed 27:58 at the end

same for map_nt: 46:05 on lb, 46:06 ingame

**Where did the bug occur**
any map

**To Reproduce**
play
get wr or lb time
check ingame time
check lb time
realize

**Expected behavior**

**Screenshots**

**Additional context**
![image](https://user-images.githubusercontent.com/90960152/144714483-b1be2252-f93a-42af-8f9c-a7b5ca0bb5ed.png)
ingame^^^

![image](https://user-images.githubusercontent.com/90960152/144714490-06b319ea-4594-4215-8361-e6a4df1f9265.png)

lbss^^^^^^^^

**Comment by nekorii04** [comment]
amogus

**Comment by nekorii04** [comment]
amongus
